name: awesomeimage
favicon: null
layout_spectrum: 0.23764004022814333
typography_spectrum: 0.3383814108092338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#2b9044'
    - '#b9b6bd'
    - '#000000'
    - '#523827'
  brandStrength: 0.6655185776762664
  lightness: 0.8693586243316531
  saturation: 0.30930869234725833
  rhythmicContrast: 0.7760358781088144
purpose: []
