name: awesomeimage
favicon: null
layout_spectrum: 0.2376400402281433
typography_spectrum: 0.3383814108092338
title: 'Your Awesome Image '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F0F0F0'
    - '#010101'
    - '#C6C5BE'
    - '#D0A289'
    - '#5B5A5B'
  brandStrength: 0.4375
  lightness: 0.8693586243316531
  saturation: 0.3093086923472583
  rhythmicContrast: 0.7760358781088144
purpose: []
